using Godot;

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT DIRECTLY. */
namespace MartKeeper;

public static class InputAction
{
  public static readonly string LEFT = "left";
  public static readonly string RIGHT = "right";
  public static readonly string UP = "up";
  public static readonly string DOWN = "down";
  public static readonly string INTERACT = "interact";
  public static readonly string[] All = { LEFT, RIGHT, UP, DOWN, INTERACT };
}
