using Godot;

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT DIRECTLY. */
namespace MartKeeper;

public readonly struct TrKey
{
    private readonly string _value;
    private TrKey(string value) => _value = value;

    // --- Generated Keys ---
    public static readonly TrKey HELLO_WORLD = new TrKey("HELLO_WORLD");
    public static readonly TrKey BANANA = new TrKey("BANANA");

    // --- Localization Logic ---

    /// <summary>
    /// Implicit conversion for standard translations: label.Text = TR.HELLO;
    /// </summary>
    public static implicit operator string(TrKey key) 
    {
        return TranslationServer.Translate(key._value);
    }

    public string GetRaw() => _value;
    public override string ToString() => (string)this;
}

public static class TR
{
    public static TrKey HELLO_WORLD => TrKey.HELLO_WORLD;
    public static TrKey BANANA => TrKey.BANANA;
}