using Godot;

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT DIRECTLY. */
namespace Martkeeper.Types;

public readonly struct TrKey
{
  private readonly string _value;

  private TrKey(string value) => _value = value;

  // --- Generated Keys ---
  public static readonly TrKey BANANA = "BANANA";
  public static readonly TrKey BREAD = "BREAD";
  public static readonly TrKey ORANGE_JUICE = "ORANGE_JUICE";
  public static readonly TrKey VIDEO_TITLE = "VIDEO_TITLE";
  public static readonly TrKey RESOLUTION_TITLE = "RESOLUTION_TITLE";
  public static readonly TrKey FULLSCREEN_TITLE = "FULLSCREEN_TITLE";
  public static readonly TrKey AUDIO_TITLE = "AUDIO_TITLE";
  public static readonly TrKey MAIN_VOLUME_TITLE = "MAIN_VOLUME_TITLE";
  public static readonly TrKey MUSIC_VOLUME_TITLE = "MUSIC_VOLUME_TITLE";
  public static readonly TrKey QUIT = "QUIT";
  public static readonly TrKey QUIT_CONFIRMATION_MESSAGE = "QUIT_CONFIRMATION_MESSAGE";
  public static readonly TrKey PAUSED_TITLE = "PAUSED_TITLE";
  public static readonly TrKey RESUME_TITLE = "RESUME_TITLE";
  public static readonly TrKey QUIT_TO_MAIN_MENU = "QUIT_TO_MAIN_MENU";
  public static readonly TrKey QUIT_TO_MENU_CONFIRMATION_MESSAGE =
    "QUIT_TO_MENU_CONFIRMATION_MESSAGE";

  // --- Localization Logic ---

  /// <summary>
  /// Implicit conversion for standard translations: label.Text = TR.HELLO;
  /// </summary>
  public static implicit operator string(TrKey key)
  {
    return TranslationServer.Translate(key._value);
  }

  public static implicit operator TrKey(string value)
  {
    return new TrKey(value);
  }

  public string GetRaw() => _value;

  public override string ToString() => (string)this;
}

public static class TR
{
  public static TrKey BANANA => TrKey.BANANA;
  public static TrKey BREAD => TrKey.BREAD;
  public static TrKey ORANGE_JUICE => TrKey.ORANGE_JUICE;
  public static TrKey VIDEO_TITLE => TrKey.VIDEO_TITLE;
  public static TrKey RESOLUTION_TITLE => TrKey.RESOLUTION_TITLE;
  public static TrKey FULLSCREEN_TITLE => TrKey.FULLSCREEN_TITLE;
  public static TrKey AUDIO_TITLE => TrKey.AUDIO_TITLE;
  public static TrKey MAIN_VOLUME_TITLE => TrKey.MAIN_VOLUME_TITLE;
  public static TrKey MUSIC_VOLUME_TITLE => TrKey.MUSIC_VOLUME_TITLE;
  public static TrKey QUIT => TrKey.QUIT;
  public static TrKey QUIT_CONFIRMATION_MESSAGE => TrKey.QUIT_CONFIRMATION_MESSAGE;
  public static TrKey PAUSED_TITLE => TrKey.PAUSED_TITLE;
  public static TrKey RESUME_TITLE => TrKey.RESUME_TITLE;
  public static TrKey QUIT_TO_MAIN_MENU => TrKey.QUIT_TO_MAIN_MENU;
  public static TrKey QUIT_TO_MENU_CONFIRMATION_MESSAGE => TrKey.QUIT_TO_MENU_CONFIRMATION_MESSAGE;
}

public static class Locale
{
  public static readonly string EN = "en";
  public static readonly string PT = "pt";
  public static readonly string DE = "de";

  public static readonly string[] All = { EN, PT, DE };
}
