using Godot;

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT DIRECTLY. */
namespace MartKeeper.Types;

public readonly struct TrKey
{
  private readonly string _value;
  private TrKey(string value) => _value = value;

  // --- Generated Keys ---
  public static readonly TrKey BANANA = new TrKey("BANANA");
  public static readonly TrKey BREAD = new TrKey("BREAD");
  public static readonly TrKey ORANGE_JUICE = new TrKey("ORANGE_JUICE");
  public static readonly TrKey VIDEO_TITLE = new TrKey("VIDEO_TITLE");
  public static readonly TrKey RESOLUTION_TITLE = new TrKey("RESOLUTION_TITLE");
  public static readonly TrKey FULLSCREEN_TITLE = new TrKey("FULLSCREEN_TITLE");
  public static readonly TrKey AUDIO_TITLE = new TrKey("AUDIO_TITLE");
  public static readonly TrKey MAIN_VOLUME_TITLE = new TrKey("MAIN_VOLUME_TITLE");
  public static readonly TrKey MUSIC_VOLUME_TITLE = new TrKey("MUSIC_VOLUME_TITLE");

  // --- Localization Logic ---

  /// <summary>
  /// Implicit conversion for standard translations: label.Text = TR.HELLO;
  /// </summary>
  public static implicit operator string(TrKey key) 
  {
    return TranslationServer.Translate(key._value);
  }

  public string GetRaw() => _value;
  public override string ToString() => (string)this;
}

public static class TR
{
  public static TrKey BANANA => TrKey.BANANA;
  public static TrKey BREAD => TrKey.BREAD;
  public static TrKey ORANGE_JUICE => TrKey.ORANGE_JUICE;
  public static TrKey VIDEO_TITLE => TrKey.VIDEO_TITLE;
  public static TrKey RESOLUTION_TITLE => TrKey.RESOLUTION_TITLE;
  public static TrKey FULLSCREEN_TITLE => TrKey.FULLSCREEN_TITLE;
  public static TrKey AUDIO_TITLE => TrKey.AUDIO_TITLE;
  public static TrKey MAIN_VOLUME_TITLE => TrKey.MAIN_VOLUME_TITLE;
  public static TrKey MUSIC_VOLUME_TITLE => TrKey.MUSIC_VOLUME_TITLE;
}

public static class Locale
{
  public static readonly string EN = "en";
  public static readonly string PT = "pt";
  public static readonly string DE = "de";

  public static readonly string[] All = { EN, PT, DE };
}
